version: '3'
services:
  php-base:
    build: php-base
    image: avcsh/savec-php-base

  php-dev:
    build: php-dev
    image: avcsh/savec-php-dev
    depends_on:
      - php-base

  php-xdebug:
    build: php-xdebug
    image: avcsh/savec-php-xdebug
    depends_on:
      - php-dev

  php-nginx-prod:
    build: php-nginx-prod
    image: avcsh/savec-php-nginx-prod
    depends_on:
      - php-base

